name: Deploy Jekyll site

on:
  push:
    branches:
      - master  # trigger on push to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup Ruby environment
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3  # match your local version

      # 3Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Install ImageMagick for al-folio webp generation
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      # Build Jekyll site
      - name: Build site
        run: bundle exec jekyll build

      # 6️⃣ Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          user_name: github-actions
          user_email: github-actions@github.com

